version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: nestdb
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestdb
    ports:
      - "5499:5432"

volumes:
  postgres_data: